language: node_js

node_js:
    - "node"
    - "11"
    - "10"

sudo: false

git:
    submodules: false

before_script:
    - npm install
    # - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
    # - mkdir geckodriver
    # - tar -xzf geckodriver-v0.27.0-linux64.tar.gz -C geckodriver
    # - export PATH=$PATH:$PWD/geckodriver
    # - ng serve -prod=true

script:
    - npm test
