language: node_js

node_js:
    - "node"
    - "11"
    - "10"

sudo: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
    - sudo mv geckodriver /usr/local/bin
  # - # start your web application and listen on `localhost`
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=4200 http://localhost &
  # ⋮

install:
    - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

# after_success:
#     - npm run report-coveralls
#     - npm run report-codecov
