language: node_js

node_js:
    - "node"
    - "11"
    - "10"

sudo: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

git:
    submodules: false

before_script:
    - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

after_success:
    - npm run report-coveralls
    - npm run report-codecov

cache:
  directories:
    - ./node_modules
