language: node_js

node_js:
    - "node"
    - "11"
    - "10"

sudo: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
    - npm install

script:
  -  mocha test/**/*.js --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
