language: node_js

node_js:
    - "node"
    - "11"
    - "10"

sudo: required

install:
    - npm install

before_script:
    - npm install -g @angular/cli

script:
    - npm test
    - ng build --prod --base-href https://github.com/nilshollmer/me-angular
